AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DomainName:
    Type: String
    Default: sheetmaxxing.com
  HostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub 'www.${DomainName}'
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub 'www.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
